<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@yield('title')</title>
    <style>
        * { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        body { margin: 0; padding: 20px; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .mb-2 { margin-bottom: 8px; }
        .mb-3 { margin-bottom: 16px; }
        .border { border: 1px solid #ddd; }
        .p-1 { padding: 4px; }
        .p-2 { padding: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 6px; vertical-align: top; }
        th { background-color: #f8f8f8; }
    </style>
</head>
<body>

    <div class="text-center mb-3">
        <h2>@yield('document_title')</h2>
        <p>@yield('document_code')</p>
    </div>

    <div class="mb-2">
        @yield('document_info')
    </div>

    <div class="mb-3">
        @yield('document_table')
    </div>

    <div class="mb-3">
        @yield('document_summary')
    </div>

    <div class="text-center">
        @yield('footer_text', 'Generated by LOVA ERP.')
    </div>

</body>
</html>
